### PR TITLE
Timezone support

### PR DESCRIPTION
**Pull request by freezy-sk**
Timezone param is sent when timezone is specified, but it was not passed to calendar event.
Datetimes returned from event entity were formatted as in UTC timezone, but actually they were just losing their offset.
That's all fixed with this pull request, following FullCalendar docs https://fullcalendar.io/docs/timeZone

### CODE REVIEW

**Comment by tattali** [comment]
can you add tests with different timezones?

**Comment by freezy-sk** [comment]
@tattali of course. do you want come complex testing or just unit tests?

**Comment by tattali** [comment]
what do you mean about complex testing ?

**Comment by Grumshruk** [comment]
Will be nice to fix and merge this feature, highly needed to prevent people to use whatever timezone they want without any trouble.

**Comment by freezy-sk** [comment]
@tattali under complex testing I meant something like integration tests with JS library

**Comment by tattali** [comment]
there are no js in this project, php unit testing is enough

**Comment by danaki** [comment]
Hello, what is the status of this issue?

**Comment by danaki** [comment]
```
129.90s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out
0.00s0.02s$ phpenv global 7.3
rbenv: version `7.3' not installed
The command "phpenv global 7.3" failed and exited with 1 during .
```

Is just a technical issue of CI. Can you please let it go?

**Comment by tattali** [comment]
This is not really a CI issue, there is just no tests for this feature

**Comment by danaki** [comment]
There's not much to test, it just adds passed parameter.

**Comment by haivala** [comment]
Can we please have this feature. Highly needed!

**Comment by fcaraballo** [comment]
is this still going on?

**Comment by tattali** [comment]
Close for inactivity

**Pull request closed without merging**
